import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {atlasAssetUrl,withAtlasAssetBase} from './atlas-assets';
import {HOMER_INJURIES,resolveHomerInjury,resolveHomerInjuries,type HomerInjuryId} from './injuries';
import {HomerSurfaceReference,SurfaceControls,SURFACE_FINDINGS,type SurfaceFindingId} from './surface';
import './injuries.css';
import './surface.css';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0,selectionMode:'anatomy'};
const injurySections=['Head & brain','Rib cage','Chest'] as const;
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const [layerView,setLayerView]=useState<'systems'|'injuries'>('systems'),[injuryMode,setInjuryMode]=useState<'internal'|'surface'>('internal'),[activeInjuries,setActiveInjuries]=useState<HomerInjuryId[]>([]),[focusedInjury,setFocusedInjury]=useState<HomerInjuryId|null>(null),[activeSurface,setActiveSurface]=useState<SurfaceFindingId[]>([]),[focusedSurface,setFocusedSurface]=useState<SurfaceFindingId|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setActiveInjuries([]);setFocusedInjury(null);setActiveSurface([]);setFocusedSurface(null);setInjuryMode('internal');setState({...initial,visible:DEFAULT_VISIBLE});fetch(atlasAssetUrl('/models/atlas.json',document.baseURI),{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(withAtlasAssetBase(data as Atlas,document.baseURI))).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const injuryMatches=useMemo(()=>new Map(HOMER_INJURIES.map(injury=>[injury.id,atlas?resolveHomerInjury(atlas,injury.id):[]])),[atlas]);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const currentInjury=focusedInjury?HOMER_INJURIES.find(item=>item.id===focusedInjury):undefined;
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const clearInjuryContext=()=>{setActiveInjuries([]);setFocusedInjury(null);};
 const clearSurfaceContext=()=>{setActiveSurface([]);setFocusedSurface(null);};
 const leaveSurface=()=>{if(state.selectionMode==='surface')setState(s=>({...s,visible:DEFAULT_VISIBLE,selected:[],isolate:false,selectionMode:'anatomy',view:'three-quarter',reset:s.reset+1}));setInjuryMode('internal');clearSurfaceContext();};
 const choose=(c:Concept)=>{clearInjuryContext();leaveSurface();setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false,selectionMode:'anatomy'}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;clearInjuryContext();leaveSurface();setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false,selectionMode:'anatomy'}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{clearInjuryContext();leaveSurface();setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id],selectionMode:'anatomy'}));};
 const applyInjuries=(next:HomerInjuryId[],focus:HomerInjuryId|null)=>{if(!atlas)return;clearSurfaceContext();setInjuryMode('internal');const ids=resolveHomerInjuries(atlas,next);setActiveInjuries(next);setFocusedInjury(focus);const injury=focus?HOMER_INJURIES.find(item=>item.id===focus):undefined;setChosen(ids.length?{id:`injury:${focus??'multiple'}`,name:injury?.name??'Homer injury reference',elements:ids}:null);setDetails(false);setState(s=>({...s,selected:ids,isolate:ids.length>0,visible:DEFAULT_VISIBLE,explode:0,rotate:false,selectionMode:ids.length?'injury':'anatomy',reset:s.reset+1}));};
 const toggleInjury=(id:HomerInjuryId,enabled:boolean)=>{const next=enabled?[...activeInjuries.filter(x=>x!==id),id]:activeInjuries.filter(x=>x!==id);applyInjuries(next,enabled?id:(focusedInjury===id?(next.at(-1)??null):focusedInjury));};
 const isolateInjury=(id:HomerInjuryId)=>applyInjuries([id],id);
 const enterSurface=()=>{clearInjuryContext();setInjuryMode('surface');setDetails(false);setChosen(null);setState(s=>({...s,visible:['integumentary'],selected:[],isolate:false,explode:0,view:'front',rotate:false,selectionMode:'surface',reset:s.reset+1}));};
 const focusSurface=(id:SurfaceFindingId)=>{setFocusedSurface(id);if(!activeSurface.includes(id))setActiveSurface(list=>[...list,id]);};
 const toggleSurface=(id:SurfaceFindingId,enabled:boolean)=>{setActiveSurface(list=>enabled?[...list.filter(x=>x!==id),id]:list.filter(x=>x!==id));if(enabled)setFocusedSurface(id);else if(focusedSurface===id)setFocusedSurface(null);};
 const showAllSurface=()=>{setActiveSurface(SURFACE_FINDINGS.map(f=>f.id));setFocusedSurface('left-face');};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);setInjuryMode('internal');clearInjuryContext();clearSurfaceContext();};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const showSystems=()=>{leaveSurface();clearInjuryContext();setLayerView('systems');};
 return <main className={`studio ${state.selectionMode==='surface'?'surface-mode':''}`}>
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> COURTROOM DEMO · PREVIEW</div><h1>Homer Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">Reference anatomy <span>·</span> <span className="injury-status">{state.selectionMode==='surface'?'Body surface demonstrative':'Homer injury isolation controls'}</span></div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="About this atlas" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label={layerView==='systems'?'Anatomical systems':"Homer's injuries"}>
   <div className="panel-tabs" role="tablist" aria-label="Atlas layers"><Button variant="ghost" role="tab" aria-selected={layerView==='systems'} className={layerView==='systems'?'active':''} onClick={showSystems}>Systems</Button><Button variant="ghost" role="tab" aria-selected={layerView==='injuries'} className={`injury-tab ${layerView==='injuries'?'active':''}`} onClick={()=>setLayerView('injuries')}>Homer&apos;s Injuries<span className="injury-badge">{HOMER_INJURIES.length}</span></Button></div>
   {layerView==='systems'?<>
    <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>{clearInjuryContext();leaveSurface();setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id),selectionMode:'anatomy'}));}}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>{clearInjuryContext();leaveSurface();setState(s=>({...s,selected:[],isolate:false,visible:['skeletal'],selectionMode:'anatomy'}));}}>Skeleton</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>{clearInjuryContext();leaveSurface();setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive'],selectionMode:'anatomy'}));}}>Organs</Button></div>
    <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>{clearInjuryContext();leaveSurface();setState(v=>({...v,visible:[s.id],isolate:false,selected:[],selectionMode:'anatomy'}));}}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
    <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>{clearInjuryContext();leaveSurface();setState(s=>({...s,visible:[],selected:[],isolate:false,selectionMode:'anatomy'}));}}>Hide all</Button></div>
   </>:<>
    <div className="injury-mode-tabs" role="tablist" aria-label="Homer injury mode"><Button variant="ghost" role="tab" aria-selected={injuryMode==='internal'} className={injuryMode==='internal'?'active':''} onClick={()=>{leaveSurface();setInjuryMode('internal');}}>Internal</Button><Button variant="ghost" role="tab" aria-selected={injuryMode==='surface'} className={injuryMode==='surface'?'active':''} onClick={enterSurface}>Body Surface</Button></div>
    {injuryMode==='internal'?<><div className="injury-intro"><strong>Documented injury references</strong>Use the switches together or tap a row to isolate one injury group. Strong color identifies the active injury reference; exact lesion overlays come next.</div><div className="injury-list">{injurySections.map(section=><div className="injury-section" key={section}><div className="injury-section-title">{section}</div>{HOMER_INJURIES.filter(injury=>injury.section===section).map(injury=>{const ids=injuryMatches.get(injury.id)??[],active=activeInjuries.includes(injury.id);return <div className={`injury-row ${active?'active':''} ${ids.length?'':'missing'}`} key={injury.id}><Button variant="ghost" className="injury-main" disabled={!ids.length} onClick={()=>isolateInjury(injury.id)} title={injury.description}><span className="injury-swatch" style={{background:injury.color}}/><span className="injury-copy"><strong>{injury.shortName}</strong><small>{ids.length?`${ids.length} ${ids.length===1?'piece':'pieces'} · tap to isolate`:'reference mesh not resolved'}</small></span></Button><Switch disabled={!ids.length} checked={active} onCheckedChange={value=>toggleInjury(injury.id,!!value)} aria-label={`Show ${injury.name}`} /></div>;})}</div>)}</div><div className="injury-foot"><span>{activeInjuries.length?`${activeInjuries.length} injury ${activeInjuries.length===1?'group':'groups'} isolated`:'Choose an injury group'}</span><Button variant="ghost" disabled={!activeInjuries.length} onClick={()=>applyInjuries([],null)}>Clear injuries</Button></div></>:<SurfaceControls active={activeSurface} focused={focusedSurface} onToggle={toggleSurface} onFocus={focusSurface} onShowAll={showAllSurface}/>} 
   </>}
  </section>
  {layerView==='injuries'&&injuryMode==='surface'&&<HomerSurfaceReference active={activeSurface} focused={focusedSurface} onFocus={focusSurface}/>} 
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Heart, femur, cranial nerve…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.selectionMode==='surface'?'HOMER · BODY SURFACE':state.isolate?(currentInjury?.shortName??chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':'ADULT HUMAN · MALE'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open atlas layers"><Layers3 size={20}/><span>Layers</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'2,234'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''} ${state.selectionMode==='injury'?'injury-detail':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{currentInjury?.description??(chosen&&selected?explanation(chosen.name,selected.system):'')}</SheetDescription>{currentInjury&&<span className="context-note">{currentInjury.evidenceNote}</span>}{chosen&&!currentInjury&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}<div className="structure-meta"><span>Atlas reference<strong>{currentInjury?'ME reference anatomy':chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false,selectionMode:'anatomy'}));setDetails(false);clearInjuryContext();}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A body, revealed.</SheetTitle><SheetDescription>Explore the adult male reference anatomy from BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>Male · BodyParts3D</strong><br/>2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy.</p><p>This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once.</p><p>Homer&apos;s Injuries uses documented ME groupings to isolate reference anatomy. Strong color identifies which reference group is active; it does not claim that the entire colored structure is injured. Precise regional overlays are a separate courtroom layer.</p><p>The Body Surface demonstrative uses a user-supplied non-photorealistic cartoon only for a slight visual resemblance. It is not a biometric reconstruction or medical photograph. Surface overlay size and color are presentation choices; internal soft-tissue findings are shown schematically.</p><p>Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.</p><h3>Source</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Original geometry & metadata <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Read the source publication <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
