import {InspectionControls} from './inspection-controls';
import {inspectionGroups,partIsVisible,type Inspection,type DetailStatus} from './inspection';
import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {atlasAssetUrl,withAtlasAssetBase} from './atlas-assets';
import {HOMER_INJURIES,resolveHomerInjury,resolveHomerInjuries,type HomerInjuryId} from './injuries';
import {connectInjuryBotHost,readInjuryBotHostConfig,type AppliedInjury,type GeneratedInjury,type HostedCaseContext} from './injurybot-bridge';
import {InjuryPanel,type InjuryTab} from './injury-panel';
import {matchInjuriesLocally,type InjuryMatch} from './injury-library';
import './injuries.css';
import './mobile.css';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronDown,ChevronRight,Focus,Layers3,Maximize2,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0,selectionMode:'anatomy',sourceDetail:true,hiddenParts:[],skullReveal:0,registrationTest:false,inspection:null};
const injurySections=['Head & brain','Rib cage','Chest'] as const;
/** "Cortez's" from a client or case name; falls back to the case itself. */
const possessive=(name?:string|null)=>{const last=(name??'').trim().split(/\s+/).filter(Boolean).at(-1);return last?`${last}${/s$/i.test(last)?'’':'’s'}`:null;};
export default function Home(){
 const hostConfig=useMemo(()=>readInjuryBotHostConfig(location.search),[]);
 const [hostedCase,setHostedCase]=useState<HostedCaseContext|null>(hostConfig.initialCase?{...hostConfig.initialCase,findings:[],activeReferenceGroups:[],appliedInjuries:[],generatedInjuries:[]}:null);
 const [applied,setApplied]=useState<AppliedInjury[]>([]),[generated,setGenerated]=useState<GeneratedInjury[]>([]),[isolated,setIsolated]=useState(false),[injuryTab,setInjuryTab]=useState<InjuryTab>('client');
 const matchRequests=useRef(new Map<string,(result:InjuryMatch)=>void>());
 const hostBridge=useRef<ReturnType<typeof connectInjuryBotHost>>(null);
 const [detailStatus,setDetailStatus]=useState<DetailStatus>('base');
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|'explode'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const [layerView,setLayerView]=useState<'systems'|'injuries'>(hostConfig.embedded?'injuries':'systems'),[activeInjuries,setActiveInjuries]=useState<HomerInjuryId[]>([]),[focusedInjury,setFocusedInjury]=useState<HomerInjuryId|null>(null);
 useEffect(()=>{const abort=new AbortController(),test=hostConfig.embedded?null:new URLSearchParams(location.search).get('test');setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setActiveInjuries([]);setFocusedInjury(null);setState(test==='fracture'?{...initial,visible:['skeletal'],selected:['FJ3229'],isolate:true,inspection:'rib',fractureMode:true,fractureVisible:false,view:'left'}:test==='abrasion'?{...initial,visible:['integumentary'],view:'back',abrasionMode:true,abrasionVisible:true,shoulderFocus:true}: {...initial,visible:DEFAULT_VISIBLE});fetch(atlasAssetUrl('/models/atlas.json',document.baseURI),{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>{const a=withAtlasAssetBase(data as Atlas,document.baseURI);setAtlas(a);const placement=hostConfig.embedded?new URLSearchParams(location.search).get('placement'):null;if(placement&&a.parts.some(p=>p.id===placement))setState({...initial,selected:[placement],isolate:true,visible:DEFAULT_VISIBLE,view:'three-quarter'});if(test==='sah')setState({...initial,sahMode:true,sahVisible:true,isolate:true,selected:inspectionGroups(a).brain,inspection:'brain',view:'three-quarter'});}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[hostConfig.embedded]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const inspectionSkullIds=useMemo(()=>new Set(atlas?inspectionGroups(atlas).skull:[]),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const injuryMatches=useMemo(()=>new Map(HOMER_INJURIES.map(injury=>[injury.id,atlas?resolveHomerInjury(atlas,injury.id):[]])),[atlas]);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const currentInjury=focusedInjury?HOMER_INJURIES.find(item=>item.id===focusedInjury):undefined;
 const visibleCount=atlas?.parts.filter(p=>partIsVisible(p,state,inspectionSkullIds.has(p.id))).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const clearInjuryContext=()=>{setActiveInjuries([]);setFocusedInjury(null);};
 const clearInspection={sahFocus:false,inspection:null,hiddenParts:[],skullReveal:0,registrationTest:false};
 const inspect=(mode:Inspection)=>{if(!atlas)return;clearInjuryContext();const ids=inspectionGroups(atlas)[mode];setChosen({id:`inspection:${mode}`,name:mode==='rib'?'Left second rib':mode==='ribcage'?'Rib cage':mode==='relationship'?'Brain and cranial assembly':mode==='skull'?'Skull skeletal structures':'Brain',elements:ids});setDetails(false);setState(s=>({...s,...clearInspection,inspection:mode,selected:ids,isolate:true,explode:0,rotate:false,selectionMode:'anatomy',view:'three-quarter',reset:s.reset+1}));};
 const choose=(c:Concept)=>{clearInjuryContext();setChosen(c);setState(s=>({...s,...clearInspection,selected:c.elements,isolate:false,rotate:false,selectionMode:'anatomy'}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string,point?:number[],normal?:number[])=>{const p=parts.get(id);if(!p)return;clearInjuryContext();setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,...clearInspection,selected:[id],isolate:s.isolate,rotate:false,selectionMode:'anatomy'}));setDetails(!new URLSearchParams(location.search).has('placement'));setPanel(null);hostBridge.current?.selection(hostedCase?.id??null,[id],p.name,point,normal);};
 const toggle=(id:SystemId)=>{clearInjuryContext();setDetails(false);setState(s=>({...s,...clearInspection,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id],selectionMode:'anatomy'}));};
 const applyInjuries=(next:HomerInjuryId[],focus:HomerInjuryId|null)=>{if(!atlas)return;const ids=resolveHomerInjuries(atlas,next);setActiveInjuries(next);setFocusedInjury(focus);const injury=focus?HOMER_INJURIES.find(item=>item.id===focus):undefined;setChosen(ids.length?{id:`injury:${focus??'multiple'}`,name:injury?.name??'Homer injury reference',elements:ids}:null);setDetails(false);setState(s=>({...s,...clearInspection,sahMode:false,sahVisible:false,selected:ids,isolate:ids.length>0,visible:DEFAULT_VISIBLE,explode:0,rotate:false,selectionMode:ids.length?'injury':'anatomy',reset:s.reset+1}));};
 const toggleInjury=(id:HomerInjuryId,enabled:boolean)=>{const next=enabled?[...activeInjuries.filter(x=>x!==id),id]:activeInjuries.filter(x=>x!==id);applyInjuries(next,enabled?id:(focusedInjury===id?(next.at(-1)??null):focusedInjury));};
 const isolateInjury=(id:HomerInjuryId)=>applyInjuries([id],id);
 /** Applied injuries drive the model: visible ones are highlighted, a focused one or "Isolate injuries" isolates. */
 const syncApplied=(next:AppliedInjury[],focus:HomerInjuryId|null,isolateAll:boolean,notify:boolean)=>{
  if(!atlas)return;
  const known=next.filter(item=>HOMER_INJURIES.some(entry=>entry.id===item.id));
  const visible=known.filter(item=>!item.hidden).map(item=>item.id as HomerInjuryId);
  const focusId=focus&&visible.includes(focus)?focus:null,ids=resolveHomerInjuries(atlas,focusId?[focusId]:visible);
  setApplied(known);setIsolated(isolateAll);setActiveInjuries(visible);setFocusedInjury(focusId);
  const injury=focusId?HOMER_INJURIES.find(item=>item.id===focusId):undefined;
  setChosen(ids.length?{id:`injury:${focusId??'applied'}`,name:injury?.name??'Applied injuries',elements:ids}:null);setDetails(false);
  setState(s=>({...s,...clearInspection,sahMode:false,sahVisible:false,selected:ids,isolate:ids.length>0&&(!!focusId||isolateAll),visible:DEFAULT_VISIBLE,rotate:false,selectionMode:ids.length?'injury':'anatomy',reset:s.reset+1}));
  if(notify&&hostedCase)hostBridge.current?.injuriesApplied(hostedCase.id,known);
 };
 const pendingGeneration=useRef<{resolve:()=>void;reject:(e:Error)=>void;timer:number}|null>(null);
 const receivedContext=useRef(''),appliedSnapshot=useRef('');
 useEffect(()=>{if(!atlas)return;hostBridge.current=connectInjuryBotHost(hostConfig,{
  context:context=>{setHostedCase(context);setGenerated(context.generatedInjuries);const groups=context.activeReferenceGroups.filter((id):id is HomerInjuryId=>HOMER_INJURIES.some(item=>item.id===id));const next=[...context.appliedInjuries,...groups.filter(id=>!context.appliedInjuries.some(item=>item.id===id)).map(id=>({id,hidden:false}))];if(receivedContext.current!==context.id){setInjuryTab(next.length||context.productionInjuries?.length?'client':'apply');receivedContext.current=context.id;appliedSnapshot.current='';}if(appliedSnapshot.current!==JSON.stringify(next)){syncApplied(next,null,false,false);appliedSnapshot.current=JSON.stringify(next);}setState(s=>({...s,productionInjuries:context.productionInjuries??[]}));},
  matchResult:result=>{const resolve=matchRequests.current.get(result.requestId);if(!resolve)return;matchRequests.current.delete(result.requestId);resolve({matches:result.matches,unmatched:result.unmatched});},
  generation:message=>{if(message.caseId!==receivedContext.current)return;const pending=pendingGeneration.current;if(pending){clearTimeout(pending.timer);pendingGeneration.current=null;if(message.injury.status==='failed')pending.reject(new Error(message.injury.stage||'The injury request could not be queued.'));else pending.resolve();}setGenerated(list=>[...list.filter(item=>item.id!==message.injury.id),message.injury]);},
 });return()=>{hostBridge.current?.dispose();hostBridge.current=null;};},[atlas,hostConfig]);
 const matchInjuries=(description:string)=>new Promise<InjuryMatch>(resolve=>{
  const bridge=hostBridge.current;
  if(!bridge||!hostedCase){resolve(hostConfig.embedded?{matches:[],unmatched:description.slice(0,120)}:matchInjuriesLocally(description));return;}
  const requestId=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  const timer=window.setTimeout(()=>{if(matchRequests.current.delete(requestId))resolve(hostConfig.embedded?{matches:[],unmatched:description.slice(0,120)}:matchInjuriesLocally(description));},10000);
  matchRequests.current.set(requestId,result=>{window.clearTimeout(timer);resolve(result);});
  bridge.matchRequest(hostedCase.id,requestId,description);
 });
 const generateInjury=async(name:string,description:string)=>{
  const bridge=hostBridge.current;
  if(bridge&&hostedCase){return new Promise<void>((resolve,reject)=>{const timer=window.setTimeout(()=>{pendingGeneration.current=null;reject(new Error('Request confirmation timed out. Check Client Injuries before trying again.'));},30000);pendingGeneration.current={resolve,reject,timer};bridge.generateRequest(hostedCase.id,name,description);});}
  throw new Error("Connect to a case in injury.bot before creating an injury.");
 };
 const applyMore=(ids:HomerInjuryId[])=>{if(hostConfig.embedded&&hostedCase){hostBridge.current?.injuriesApplied(hostedCase.id,ids.map(id=>({id,hidden:false})));return;}syncApplied([...applied,...ids.filter(id=>!applied.some(item=>item.id===id)).map(id=>({id,hidden:false}))],null,isolated,true);};
 const setHidden=(id:string,hidden:boolean)=>syncApplied(applied.map(item=>item.id===id?{...item,hidden}:item),focusedInjury&&focusedInjury!==id?focusedInjury:null,isolated,true);
 const focusApplied=(id:HomerInjuryId)=>syncApplied(applied,focusedInjury===id?null:id,isolated,false);
 const toggleIsolated=()=>syncApplied(applied,null,!isolated,false);
 const [productionFocus,setProductionFocus]=useState<string|null>(null);
 const panelHidden=(id:string,hidden:boolean)=>{if(!(state.productionInjuries??[]).some(p=>p.id===id)){setHidden(id,hidden);return;}setState(s=>({...s,productionInjuries:s.productionInjuries?.map(p=>p.id===id?{...p,hidden}:p)}));if(hostConfig.parentOrigin)window.parent.postMessage({type:'human-atlas:production-visibility',version:1,caseId:hostedCase?.id,id,hidden},hostConfig.parentOrigin);};
 const panelFocus=(id:string)=>{const p=state.productionInjuries?.find(p=>p.id===id);if(!p){setProductionFocus(null);focusApplied(id as HomerInjuryId);return;}const next=productionFocus===id?null:id;setProductionFocus(next);setState(s=>({...s,selected:next?[p.parentId]:[],isolate:!!next,explode:0,reset:s.reset+1}));};
 const panelIsolate=()=>{const next=!isolated;setIsolated(next);setProductionFocus(null);const ids=[...resolveHomerInjuries(atlas!,applied.filter(p=>!p.hidden).map(p=>p.id as HomerInjuryId)),...(state.productionInjuries??[]).filter(p=>!p.hidden).map(p=>p.parentId)];setState(s=>({...s,selected:next?ids:[],isolate:next,visible:DEFAULT_VISIBLE,explode:0,reset:s.reset+1}));};
 const panelClear=()=>{clearApplied();setProductionFocus(null);setState(s=>({...s,productionInjuries:[]}));if(hostConfig.parentOrigin)window.parent.postMessage({type:'human-atlas:production-clear',version:1,caseId:hostedCase?.id},hostConfig.parentOrigin);};
 const clearApplied=()=>{setGenerated([]);syncApplied([],null,false,true);};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);clearInjuryContext();};
 const openPanel=(next:'layers'|'search'|'explode')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const showSystems=()=>{setLayerView('systems');};
 const injuryOwner=possessive(hostedCase?.client)??possessive(hostConfig.embedded?hostedCase?.title:'Homer')??'the case';
 return <main className={`studio ${hostConfig.embedded?'embedded':''}`}>
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0,layersOpen:panel==='layers'}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError} onDetailStatus={setDetailStatus}/>}
  <div className="vignette"/>
  <header className="identity">{!hostConfig.embedded&&<div className="eyebrow"><span className="status-dot"/> COURTROOM DEMO · PREVIEW</div>}<h1>{hostConfig.embedded?(hostedCase?.title??'Case Atlas'):'Homer Atlas'}</h1><div className="identity-meta">{hostConfig.embedded?'Accident injury reconstruction workspace':'Reference anatomy'} <span>·</span> <span className="injury-status review-note">{hostConfig.embedded?'Review-controlled anatomy':'Homer injury reference controls'}</span></div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button></nav>
  <section style={new URLSearchParams(location.search).has('placement')?{display:'none'}:undefined} className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label={layerView==='systems'?'Anatomical systems':'Case injuries'}>
   {panel==='layers'&&<div className="panel-bar"><strong>{hostConfig.embedded?'Injuries':'Explore'}</strong><Button variant="ghost" className="panel-minimize" onClick={()=>setPanel(null)} aria-label="Minimize explore panel"><ChevronDown size={18}/></Button></div>}
   {hostConfig.embedded&&atlas&&<InjuryPanel catalogueEntries={hostedCase?.catalogue??[]} tab={injuryTab} onTab={setInjuryTab} applied={[...applied,...(state.productionInjuries??[]).map(p=>({id:p.id,hidden:p.hidden}))]} extraEntries={(state.productionInjuries??[]).map(p=>({id:p.id,name:p.name||parts.get(p.parentId)?.name||p.parentId,shortName:p.name||parts.get(p.parentId)?.name||p.parentId,color:"#984b49",description:"Reviewed injury illustration"}))} generated={generated} pieces={new Map<string,number>([...HOMER_INJURIES.map(item=>[item.id,(injuryMatches.get(item.id)??[]).length] as [string,number]),...(state.productionInjuries??[]).map(p=>[p.id,1] as [string,number])])} isolated={isolated} focused={productionFocus||focusedInjury} onToggleHidden={panelHidden} onFocus={panelFocus} onIsolate={panelIsolate} onClear={panelClear} onApply={ids=>applyMore(ids as HomerInjuryId[])} onMatch={matchInjuries} onGenerate={generateInjury}/>}
   {!hostConfig.embedded&&<><div className="panel-tabs" role="tablist" aria-label="Atlas layers"><Button variant="ghost" role="tab" aria-selected={layerView==='systems'} className={layerView==='systems'?'active':''} onClick={showSystems}>Systems</Button><Button variant="ghost" role="tab" aria-selected={layerView==='injuries'} className={`injury-tab ${layerView==='injuries'?'active':''}`} onClick={()=>setLayerView('injuries')}>Injuries<span className="injury-badge">{HOMER_INJURIES.length}</span></Button></div>
   {!hostConfig.embedded&&<><details className="sah-controls" open={state.sahMode||undefined}><summary>Test 3 · Subarachnoid blood</summary><p>Synthetic left frontal surface collection following the modeled folds. Membranes are not modeled. Not a Homer finding.</p>
    {!state.sahMode?<Button variant="ghost" onClick={()=>{if(!atlas)return;clearInjuryContext();setDetails(false);setState(s=>({...initial,reset:s.reset+1,sahMode:true,sahVisible:true,isolate:true,selected:inspectionGroups(atlas).brain,inspection:'brain'}));}}>Start hemorrhage test</Button>:<>
     <div className="inspection-option"><span>Synthetic blood collection</span><Switch aria-label="Show test hemorrhage" checked={!!state.sahVisible} onCheckedChange={v=>setState(s=>({...s,sahVisible:!!v}))}/></div>
     <div className="inspection-presets">{(['Skull on','Skull cutaway','Isolate brain'] as const).map((label,i)=><Button variant="ghost" key={label} onClick={()=>{if(!atlas)return;setDetails(false);setState(s=>({...s,sahFocus:false,inspection:i===2?'brain':'relationship',selected:inspectionGroups(atlas)[i===2?'brain':'relationship'],isolate:true,hiddenParts:[],skullReveal:i===1?.65:0,explode:0,reset:s.reset+1}));}}>{label}</Button>)}<Button variant="ghost" onClick={()=>setState(s=>({...s,abrasionTurn:(s.abrasionTurn??0)+1}))}>Rotate brain 360°</Button><Button variant="ghost" onClick={()=>{if(!atlas)return;setDetails(false);setState(s=>({...s,sahFocus:true,selected:inspectionGroups(atlas).brain,isolate:true,skullReveal:0,inspection:'brain',explode:0,reset:s.reset+1}));}}>Inspect blood</Button></div>
     <div className="skull-reveal"><label id="sah-explode">Explode test anatomy</label><Slider aria-labelledby="sah-explode" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,sahFocus:false,explode:(Array.isArray(v)?v[0]:v)/100}))}/></div>
     <Button variant="ghost" onClick={reset}>Exit hemorrhage test</Button>
    </>}
   </details>
   <details className="fracture-controls" open={state.fractureMode||undefined}><summary>Test 2 · Rib fracture</summary><p>Synthetic fracture · left second rib, lateral shaft. Illustrative break and cut faces, not a Homer finding.</p>
    {!state.fractureMode?<Button variant="ghost" onClick={()=>{setDetails(false);setState(s=>({...initial,reset:s.reset+1,visible:['skeletal'],selected:['FJ3229'],isolate:true,inspection:'rib',fractureMode:true,fractureVisible:false,view:'left'}));}}>Start fracture test</Button>:<>
     <div className="inspection-option"><span>Localized fracture</span><Switch aria-label="Show test fracture" checked={!!state.fractureVisible} onCheckedChange={v=>setState(s=>({...s,fractureVisible:!!v}))}/></div>
     <div className="inspection-presets"><Button variant="ghost" onClick={()=>setState(s=>({...s,fractureFocus:false,view:'left',reset:s.reset+1}))}>Whole rib</Button><Button variant="ghost" onClick={()=>setState(s=>({...s,fractureFocus:true,reset:s.reset+1}))}>Inspect fracture</Button><Button variant="ghost" onClick={()=>setState(s=>({...s,abrasionTurn:(s.abrasionTurn??0)+1}))}>Rotate rib 360°</Button></div>
     <Button variant="ghost" onClick={reset}>Exit fracture test</Button>
    </>}
   </details>
   <details className="abrasion-controls" open={state.abrasionMode||undefined}><summary>Test 1 · Surface abrasion</summary><p>Synthetic road rash · patient left posterior shoulder. Not a Homer finding.</p>
    {!state.abrasionMode?<Button variant="ghost" onClick={()=>setState(s=>({...initial,reset:s.reset+1,visible:['integumentary'],view:'back',abrasionMode:true,abrasionVisible:true,shoulderFocus:true}))}>Start abrasion test</Button>:<>
     <div className="inspection-option"><span>Test abrasion</span><Switch aria-label="Show test abrasion" checked={!!state.abrasionVisible} onCheckedChange={v=>setState(s=>({...s,abrasionVisible:!!v}))}/></div>
     <div className="inspection-presets"><Button variant="ghost" onClick={()=>setState(s=>({...s,shoulderFocus:true,view:'back',reset:s.reset+1}))}>Focus shoulder</Button><Button variant="ghost" onClick={()=>setState(s=>({...s,shoulderFocus:false,view:'back',reset:s.reset+1}))}>Whole body</Button><Button variant="ghost" onClick={()=>setState(s=>({...s,abrasionTurn:(s.abrasionTurn??0)+1}))}>Rotate 360°</Button></div>
     <div className="skull-reveal"><label id="abrasion-explode">Explode test anatomy</label><Slider aria-labelledby="abrasion-explode" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100}))}/></div>
     <Button variant="ghost" onClick={reset}>Exit abrasion test</Button>
    </>}
   </details></>}
   {layerView==='systems'?<>
    {atlas&&<InspectionControls atlas={atlas} state={state} detailStatus={detailStatus} onInspect={inspect} onChange={patch=>setState(s=>({...s,...patch}))} onRestore={reset}/>}
    <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>{clearInjuryContext();setState(s=>({...s,...clearInspection,selected:[],isolate:false,visible:activeSystems.map(x=>x.id),selectionMode:'anatomy'}));}}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>{clearInjuryContext();setState(s=>({...s,...clearInspection,selected:[],isolate:false,visible:['skeletal'],selectionMode:'anatomy'}));}}>Skeleton</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>{clearInjuryContext();setState(s=>({...s,...clearInspection,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive'],selectionMode:'anatomy'}));}}>Organs</Button></div>
    <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>{clearInjuryContext();setState(v=>({...v,...clearInspection,visible:[s.id],isolate:false,selected:[],selectionMode:'anatomy'}));}}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
    <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>{clearInjuryContext();setState(s=>({...s,...clearInspection,visible:[],selected:[],isolate:false,selectionMode:'anatomy'}));}}>Hide all</Button></div>
   </>:<>
    <details className="inspection-controls apply-injuries"><summary>Apply injuries</summary><div className="inspection-options"><p className="detail-status">Choose a predefined injury to place on the reference anatomy. Library entries created by Injury.bot and your firm will appear here as they are approved.</p><NativeSelect className="injury-library" disabled aria-label="Injury library" defaultValue=""><NativeSelectOption value="">No injuries available yet</NativeSelectOption></NativeSelect></div></details>
    <div className="injury-owner"><strong>Inspect {injuryOwner} injuries</strong><span>Reference groups pending review against the source report. No lesion placement is asserted.</span></div><div className="injury-list">{injurySections.map(section=><div className="injury-section" key={section}><div className="injury-section-title">{section}</div>{HOMER_INJURIES.filter(injury=>injury.section===section).map(injury=>{const ids=injuryMatches.get(injury.id)??[],active=activeInjuries.includes(injury.id);return <div className={`injury-row ${active?'active':''} ${ids.length?'':'missing'}`} key={injury.id}><Button variant="ghost" className="injury-main" aria-label={injury.shortName} disabled={!ids.length} onClick={()=>isolateInjury(injury.id)} title={injury.description}><span className="injury-swatch" style={{background:injury.color}}/><span className="injury-copy"><strong>{injury.shortName}</strong><small>{ids.length?`${ids.length} ${ids.length===1?'piece':'pieces'} · tap to isolate`:'reference mesh not resolved'}</small></span></Button><Switch disabled={!ids.length} checked={active} onCheckedChange={value=>toggleInjury(injury.id,!!value)} aria-label={`Show ${injury.name}`} /></div>;})}</div>)}</div><div className="injury-foot"><span>{activeInjuries.length?`${activeInjuries.length} injury ${activeInjuries.length===1?'group':'groups'} isolated`:'Choose an injury group'}</span><Button variant="ghost" disabled={!activeInjuries.length} onClick={()=>applyInjuries([],null)}>Clear injuries</Button></div> 
   </>}</>}
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Heart, femur, cranial nerve…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(isolated&&!focusedInjury&&applied.length?'ISOLATED INJURIES':currentInjury?.shortName??chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':'ADULT HUMAN · MALE'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open atlas layers">{hostConfig.embedded?<Activity size={20}/>:<Layers3 size={20}/>}<span>{hostConfig.embedded?'Injuries':'Explore'}</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <div className={`explode-dock mobile-only ${panel==='explode'?'open':''}`}>{panel==='explode'&&<div className="explode-popover glass"><output>{Math.round(state.explode*100)}<span>%</span></output><div className="explode-track"><input type="range" className="explode-vertical" min={0} max={100} step={1} value={Math.round(state.explode*100)} aria-label="Explode anatomy" onChange={e=>{const v=Number(e.target.value);setState(s=>({...s,explode:v/100,view:v>80?'front':s.view,rotate:false}));}}/></div><span>EXPLODE</span></div>}<Button variant="ghost" className={`dock-explode ${panel==='explode'?'active':''}`} aria-pressed={panel==='explode'} aria-label="Explode anatomy controls" onClick={()=>openPanel('explode')}><Maximize2 size={18}/><span>Explode</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'2,234'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''} ${state.selectionMode==='injury'?'injury-detail':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{currentInjury?.description??(chosen&&selected?explanation(chosen.name,selected.system):'')}</SheetDescription>{currentInjury&&<span className="context-note">{currentInjury.evidenceNote}</span>}{chosen&&!currentInjury&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}<div className="structure-meta"><span>Atlas reference<strong>{currentInjury?'Evidence review pending':chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false,selectionMode:'anatomy'}));setDetails(false);clearInjuryContext();}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A body, revealed.</SheetTitle><SheetDescription>Explore the adult male reference anatomy from BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>Male · BodyParts3D</strong><br/>2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy.</p><p>This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once.</p><p>Homer&apos;s Injuries retains inherited reference groups pending review against identified case evidence. No group is a verified finding or a localized lesion. Healthy anatomy remains visible without pathology coloring.</p><p>Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.</p><h3>Source</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Original geometry & metadata <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Read the source publication <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
