import {useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {atlasAssetUrl} from './atlas-assets';

export type SurfaceFindingId='scalp-abrasions'|'forehead-abrasion'|'left-face'|'tongue-lacerations'|'posterior-neck'|'upper-back'|'flank-lower-back'|'midline-lower-back';
export interface SurfaceFinding{ id:SurfaceFindingId; view:'face'|'back'; name:string; shortName:string; kind:'abrasion'|'contusion-laceration'|'laceration'|'soft-tissue'; description:string; }
export const SURFACE_FINDINGS:SurfaceFinding[]=[
 {id:'scalp-abrasions',view:'face',name:'Left frontoparietal and frontotemporal scalp abrasions',shortName:'Scalp abrasions',kind:'abrasion',description:'Broad demonstrative surface region on the patient’s left scalp. The overlay shows location, not measured abrasion size.'},
 {id:'forehead-abrasion',view:'face',name:'Left forehead abrasion',shortName:'Forehead abrasion',kind:'abrasion',description:'Surface abrasion region on the left forehead.'},
 {id:'left-face',view:'face',name:'Left facial, cheek, eyebrow and lateral periorbital contusions and lacerations',shortName:'Left face / eye / cheek',kind:'contusion-laceration',description:'Combined demonstrative zone for the documented left eyebrow, lateral periorbital, cheek and facial findings. Individual marks are illustrative rather than traced wound measurements.'},
 {id:'tongue-lacerations',view:'face',name:'Multiple left-sided tongue lacerations',shortName:'Tongue lacerations',kind:'laceration',description:'Mouth marker for the documented left-sided tongue lacerations. The closed-mouth portrait cannot display the actual tongue surface.'},
 {id:'posterior-neck',view:'back',name:'Inferior left posterior neck hemorrhage',shortName:'Posterior neck',kind:'soft-tissue',description:'Regional soft-tissue finding beneath the posterior neck surface. Shown with a translucent region because it is not an external skin wound.'},
 {id:'upper-back',view:'back',name:'Patchy multifocal hemorrhage of the left upper back',shortName:'Left upper back',kind:'soft-tissue',description:'Regional underlying hemorrhage of the left upper back, shown schematically.'},
 {id:'flank-lower-back',view:'back',name:'Left lateral flank and lower-back contusions with associated soft-tissue hemorrhage',shortName:'Left flank / lower back',kind:'contusion-laceration',description:'Surface contusion region with associated deeper soft-tissue hemorrhage on the patient’s left flank and lower back.'},
 {id:'midline-lower-back',view:'back',name:'Midline lower-back hemorrhage over the lumbar vertebrae',shortName:'Midline lower back',kind:'soft-tissue',description:'Midline lumbar soft-tissue hemorrhage region shown schematically.'},
];

export function SurfaceControls({active,focused,onToggle,onFocus,onShowAll}:{active:SurfaceFindingId[];focused:SurfaceFindingId|null;onToggle:(id:SurfaceFindingId,on:boolean)=>void;onFocus:(id:SurfaceFindingId)=>void;onShowAll:()=>void}){
 return <><div className="surface-intro"><strong>Body Surface</strong>Opaque reference skin plus demonstrative injury zones. Patient left is labeled explicitly; internal findings remain translucent.</div><div className="surface-actions"><Button variant="ghost" onClick={onShowAll}>Show all</Button><span>{active.length} active</span></div><div className="surface-list">{SURFACE_FINDINGS.map(f=><div className={`surface-row ${active.includes(f.id)?'active':''} ${focused===f.id?'focused':''}`} key={f.id}><Button variant="ghost" className="surface-main" onClick={()=>onFocus(f.id)}><span className={`surface-kind ${f.kind}`}/><span><strong>{f.shortName}</strong><small>{f.view==='face'?'Face / scalp':'Back / neck'}</small></span></Button><Switch checked={active.includes(f.id)} onCheckedChange={value=>onToggle(f.id,!!value)} aria-label={`Show ${f.name}`}/></div>)}</div></>;
}

export function HomerSurfaceReference({active,focused,onFocus}:{active:SurfaceFindingId[];focused:SurfaceFindingId|null;onFocus:(id:SurfaceFindingId)=>void}){
 const initialView=useMemo(()=>SURFACE_FINDINGS.find(f=>f.id===focused)?.view??'face',[focused]);
 const [manualView,setManualView]=useState<'face'|'back'|null>(null);const view=manualView??initialView;
 const isOn=(id:SurfaceFindingId)=>active.includes(id);const isFocused=(id:SurfaceFindingId)=>focused===id;
 return <aside className="surface-reference glass" aria-label="Homer body surface demonstrative"><div className="surface-reference-head"><div><span>BODY SURFACE DEMONSTRATIVE</span><strong>{view==='face'?'Homer · face and scalp':'Posterior surface'}</strong></div><div className="surface-view-tabs"><Button variant="ghost" className={view==='face'?'active':''} onClick={()=>setManualView('face')}>Face</Button><Button variant="ghost" className={view==='back'?'active':''} onClick={()=>setManualView('back')}>Back</Button></div></div>{view==='face'?<div className="surface-portrait"><img src={atlasAssetUrl('/homer/homer-surface-reference.jpg',document.baseURI)} alt="Stylized, non-photorealistic Homer facial reference"/><div className="patient-left">PATIENT LEFT</div>{(['scalp-abrasions','forehead-abrasion','left-face','tongue-lacerations'] as SurfaceFindingId[]).map(id=><button key={id} aria-label={SURFACE_FINDINGS.find(f=>f.id===id)!.name} onClick={()=>onFocus(id)} className={`surface-mark ${id} ${isOn(id)?'on':''} ${isFocused(id)?'focus':''}`}/>)}</div>:<div className="surface-back"><svg viewBox="0 0 220 360" role="img" aria-label="Posterior body surface reference"><path className="body-outline" d="M95 18c-17 5-27 21-27 40 0 15 7 27 18 34-24 8-43 28-49 57l-14 71c-3 17 4 28 17 31l18 4 7 76h89l7-76 18-4c13-3 20-14 17-31l-14-71c-6-29-25-49-49-57 11-7 18-19 18-34 0-19-10-35-27-40-6-2-13-2-19 0z"/><path className="spine-line" d="M110 98v202"/><text x="13" y="28">L</text><text x="195" y="28">R</text><g className={`back-zone posterior-neck ${isOn('posterior-neck')?'on':''} ${isFocused('posterior-neck')?'focus':''}`} onClick={()=>onFocus('posterior-neck')}><ellipse cx="96" cy="96" rx="22" ry="14"/></g><g className={`back-zone upper-back ${isOn('upper-back')?'on':''} ${isFocused('upper-back')?'focus':''}`} onClick={()=>onFocus('upper-back')}><ellipse cx="78" cy="154" rx="31" ry="43"/></g><g className={`back-zone flank-lower-back ${isOn('flank-lower-back')?'on':''} ${isFocused('flank-lower-back')?'focus':''}`} onClick={()=>onFocus('flank-lower-back')}><ellipse cx="73" cy="236" rx="29" ry="47"/></g><g className={`back-zone midline-lower-back ${isOn('midline-lower-back')?'on':''} ${isFocused('midline-lower-back')?'focus':''}`} onClick={()=>onFocus('midline-lower-back')}><ellipse cx="110" cy="249" rx="16" ry="38"/></g></svg></div>}<div className="surface-caption">Illustrative placement from the supplied injury diagram. Overlay size and shape do not represent measured wound dimensions. Internal soft-tissue findings are shown schematically.</div>{focused&&<div className="surface-focused"><strong>{SURFACE_FINDINGS.find(f=>f.id===focused)?.name}</strong><p>{SURFACE_FINDINGS.find(f=>f.id===focused)?.description}</p></div>}</aside>;
}
