import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
await import('./validate-surface-assets.mjs');
const page=readFileSync('app/page.tsx','utf8'),scene=readFileSync('app/scene.tsx','utf8');
assert(!page.includes('HomerSurfaceReference'),'Removed flat face/back panel must stay out of the active application');
assert(!page.includes('SurfaceControls'),'Removed Homer Body Surface tab must stay out of the active application');
assert(!scene.includes("selectionMode==='surface'"),'No Homer opaque body surface substitution');
const {SYSTEMS}=await import('../app/anatomy.ts');
assert(SYSTEMS.some(s=>s.id==='integumentary'&&s.name==='Body surface'),'Ordinary body surface system must remain');
assert(scene.includes("opacity:system==='integumentary'?.1:1"),'Ordinary skin transparency is preserved');
const css=readFileSync('app/mobile.css','utf8');
for(const token of ['.view-controls','.bottom-dock .explode-control','.bottom-dock .dock-reset','display: none !important','.dock-layers'])assert(css.includes(token));
console.log('PASS: flat Body Surface removed, ordinary skin and compact mobile controls preserved, asset safeguards retained.');
